version: "3.7"
services:
  oidc:
    image: quay.io/keycloak/keycloak:20.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
  envoy:
    image: docker.io/envoyproxy/envoy:v1.24.1
    ports:
      - "5000:5000"
      - "5001:5001"
    expose:
      - "5000"
      - "5001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      - DEBUG_LEVEL=debug
    security_opt:
      - label:disable
  opa: 
    image: openpolicyagent/opa:0.48.0-envoy-2-rootless
    volumes:
      - ./policy.rego:/config/policy.rego
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"  # default value
      - "--set=decision_logs.console=true"
      - "/config/policy.rego"
    security_opt:
      - label:disable
  app:
    ports:
      - "3000:80"
    image: kennethreitz/httpbin:latest
