version: "3.7"
services:
  oidc:
    image: quay.io/keycloak/keycloak:20.0
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
  envoy:
    build: ./compose/envoy
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/config/envoy.yaml
    environment:
      - DEBUG_LEVEL=info
      - SERVICE_NAME=app  # should match name of upstream service
      - SERVICE_PORT=80
    security_opt:
      - label:disable
  opa: 
    image: openpolicyagent/opa:0.48.0-envoy-1-rootless
    volumes:
      - ./policy.rego:/config/policy.rego
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"  # default value
      - "--set=decision_logs.console=true"
      - "/config/policy.rego"
    security_opt:
      - label:disable
  app:
    ports:
      - "8080:80"
    image: kennethreitz/httpbin:latest
