version: "3.7"
services:
  oidc:
    image: quay.io/keycloak/keycloak:20.0
    networks:
      stacknet:
        ipv4_address: 172.16.238.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
  envoy:
    image: docker.io/envoyproxy/envoy:v1.24.1
    networks:
      stacknet:
        ipv4_address: 172.16.238.3
    ports:
      - "5000:5000"
      - "5001:5001"
    command:
      - "-c /etc/envoy/envoy.yaml"
      - "--log-level info"
    expose:
      - "5000"
      - "5001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - app
      - opa
    security_opt:
      - label:disable
  opa: 
    image: docker.io/openpolicyagent/opa:0.48.0-envoy-1-rootless
    networks:
      stacknet:
        ipv4_address: 172.16.238.4
    command:
      - "run"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--disable-telemetry"
      - "--server"
      - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"  # default value
      - "--set=plugins.envoy_ext_authz_grpc.dry-run=false"
      - "--set=decision_logs.console=true"
      - "/config/policy.rego"
    volumes:
      - ./policy.rego:/config/policy.rego
    security_opt:
      - label:disable
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      stacknet:
        ipv4_address: 172.16.238.10

networks:
  stacknet:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
